// Generated by CoffeeScript 1.9.2
(function() {
  var ftacore, should;

  should = require('should');

  ftacore = require('../src/ftacore.coffee');

  describe('ftacore test', function() {
    this.timeout(10000);
    it('fireEvent', function(done) {
      var myevent;
      myevent = {
        source: 'A',
        fireTime: '2015',
        type: 'insertCard'
      };
      ftacore.fireEvent(myevent);
      return done();
    });
    it('addListener', function(done) {
      var event_string, myevent;
      event_string = 'insertPaper';
      ftacore.addListener(event_string, function(event) {
        return console.log("event is: ", event);
      });
      myevent = {
        source: 'A',
        fireTime: '2015',
        type: 'insertCard'
      };
      ftacore.fireEvent(myevent);
      return done();
    });
    it('readCard:NtCardReader', function(done) {
      var param;
      param = {
        ver: "1.1.1.1",
        timeOut: 3000,
        serviceName: "NtCardReader",
        readData: ["track2", "track3", "cardNo"]
      };
      return ftacore.readCard(param, function(error, data) {
        console.log("error: ", error);
        console.log("data: ", data);
        return done();
      });
    });
    it('readCard:NtIdentityReader', function(done) {
      var param;
      param = {
        serviceName: "NtIdentityReader",
        readData: ['idName', 'idGender', 'idFolk', 'idBirthDay', 'idAddress', 'idAgency', 'idExpireStart', 'idExpireEnd', 'idPicture']
      };
      return ftacore.readCard(param, function(error, data) {
        console.log("error: ", error);
        console.log("data: ", data);
        return done();
      });
    });
    it('readCardSync:NtCardReaderSync', function(done) {
      var param;
      param = {
        serviceName: "NtCardReader",
        readData: ["track2", "track3", "cardNo"]
      };
      console.log(ftacore.readCardSync(param));
      return done();
    });
    it('readCardSync:NtIdentityReaderSync', function(done) {
      var param;
      param = {
        serviceName: "NtIdentityReader",
        readData: ["idGender"]
      };
      console.log(ftacore.readCardSync(param));
      return done();
    });
    it('getCardReaderStatus:getNtCardReaderStatus', function(done) {
      var param;
      param = {
        serviceName: 'NtCardReader'
      };
      return ftacore.getCardReaderStatus(param, function(error, data) {
        console.log("error: ", error);
        console.log("data: ", data);
        return done();
      });
    });
    it('getCardReaderStatus:getNtIdentityReaderStatus', function(done) {
      var param;
      param = {
        serviceName: 'NtCardReader'
      };
      return ftacore.getCardReaderStatus(param, function(error, data) {
        console.log("error: ", error);
        console.log("data: ", data);
        return done();
      });
    });
    it('getCardReaderStatusSync:getNtCardReaderStatusSync', function(done) {
      var param;
      param = {
        serviceName: 'NtCardReader'
      };
      console.log(ftacore.getCardReaderStatusSync(param));
      return done();
    });
    it('operateCard', function(done) {
      var param;
      param = {
        serviceName: 'NtCardReader',
        action: 'off'
      };
      return ftacore.operateCard(param, function(err) {
        console.log(err);
        return done();
      });
    });
    it('operateCardSync', function(done) {
      var param;
      param = {
        serviceName: 'NtCardReader',
        action: 'off'
      };
      console.log(ftacore.operateCardSync(param));
      return done();
    });
    it('printData', function(done) {
      var param;
      param = {
        serviceName: 'NtDocumentPrinter',
        data: []
      };
      return ftacore.printData(param, function(err) {
        console.log(err);
        return done();
      });
    });
    it('printDataSync', function(done) {
      var param;
      param = {
        serviceName: 'NtDocumentPrinter',
        data: []
      };
      console.log(ftacore.printDataSync(param));
      return done();
    });
    it('printDimensionCodeData', function(done) {
      var param;
      param = {
        serviceName: 'NtDocumentPrinter',
        codeType: 1,
        codeImgPath: "QRcode.jpg"
      };
      return ftacore.printDimensionCodeData(param, function(err) {
        console.log(err);
        return done();
      });
    });
    it('printDimensionCodeDataSync', function(done) {
      var param;
      param = {
        serviceName: 'NtDocumentPrinter',
        codeType: 1,
        codeImgPath: "QRcode.jpg"
      };
      console.log(ftacore.printDimensionCodeDataSync(param));
      return done();
    });
    it('getPrinterStatus', function(done) {
      var param;
      param = {
        serviceName: 'NtDocumentPrinter'
      };
      return ftacore.getPrinterStatus(param, function(err) {
        console.log(err);
        return done();
      });
    });
    it('getPrinterStatusSync', function(done) {
      var param;
      param = {
        serviceName: 'NtDocumentPrinter'
      };
      console.log(ftacore.getPrinterStatusSync(param));
      return done();
    });
    it('operateCard', function(done) {
      var param;
      param = {
        serviceName: "NtDocumentPrinter",
        action: 'eject'
      };
      return ftacore.operatePrinter(param, function(err) {
        console.log(err);
        return done();
      });
    });
    return it('operatePrinterSync', function(done) {
      var param;
      param = {
        serviceName: "NtDocumentPrinter",
        action: 'eject'
      };
      console.log(ftacore.operatePrinterSync(param));
      return done();
    });
  });

}).call(this);
